name: ArgumentParser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build using Makefile
      run: make build-analyzer
    
    - name: Build tests
      run: make build-tests
      
    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal ArgumentParser.Tests
    
    - name: Build example project
      run: make build-example
    
    - name: Run integration tests (example project)
      run: |
        ExampleConsole/bin/Debug/net9.0/ExampleConsole --Target target -v 15