name: ArgumentParser deployment pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Required to push changes and tags
  id-token: write  # Required for GitVersion to work properly

jobs:
  build-check-and-tag:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # This is important for GitVersion to work properly

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9'
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Install dotnet-gitversion
      run: |
        dotnet tool install --global GitVersion.Tool
        dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: create release
      run: make release
      
    - name: Push changes and tags
      run: |
        git push
        git push --tags