name: ArgumentParser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9'

    - name: Clean all
      run: make clean
    
    - name: Build using Makefile
      run: make build-analyzer
    
    - name: Build and run tests
      run: make test
      
    - name: Build example project
      run: make build-example
    
    - name: Run integration tests (example project)
      run: |
        ExampleConsole/bin/Debug/net9.0/ExampleConsole --Target target -v 15
        ExampleConsole/bin/Debug/net9.0/ExampleConsole --Target target --Level Level3